"""Application-facing repository capabilities.

SQLiteStore currently implements all of these protocols. Keeping the
capabilities separate prevents application services from depending on the
storage implementation or on unrelated tables.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import Any, Protocol

from app.domain.models import AnalysisResult, ContentItem, EventFeatures
from app.ports.interfaces import TemplateProvider


class IntelligenceRepository(Protocol):
    def save_item(self, item: ContentItem, status: str = "discovered") -> bool: ...
    def item_status(self, item_id: str) -> str | None: ...
    def has_analysis(self, item_id: str) -> bool: ...
    def save_analysis(
        self, item_id: str, result: AnalysisResult,
        model_name: str = "unknown", prompt_version: str = "unknown",
    ) -> None: ...
    def find_recent_notification_duplicate(
        self, item: ContentItem, event: EventFeatures | None = None, lookback_hours: int = 72,
    ) -> Mapping[str, Any] | None: ...
    def save_dedup_review(
        self, item_id: str, candidate_item_id: str, relationship: str,
        confidence: float, reason: str, raw: dict,
        model_name: str = "unknown", prompt_version: str = "unknown",
    ) -> None: ...


class DeliveryRepository(Protocol):
    def queue_delivery(self, item_id: str) -> None: ...
    def pending_deliveries(self) -> Iterable[Mapping[str, Any]]: ...
    def mark_sent(self, item_id: str, message_id: str) -> None: ...
    def mark_retry(self, item_id: str, error: str, attempts: int) -> None: ...


class NotificationRepository(IntelligenceRepository, DeliveryRepository, Protocol):
    """The capabilities needed by the real-time intelligence pipeline."""


class ReportRepository(Protocol):
    def retryable_reports(self) -> Iterable[Mapping[str, Any]]: ...
    def ensure_report(
        self, report_id: str, report_type: str, period_start: str, period_end: str,
    ) -> Mapping[str, Any]: ...
    def report_candidates(
        self, period_start: str, period_end: str, limit: int = 40,
    ) -> Iterable[Mapping[str, Any]]: ...
    def save_report_payload(self, report_id: str, payload: dict, prompt_version: str) -> None: ...
    def mark_report_sent(self, report_id: str, message_id: str) -> None: ...
    def mark_report_retry(self, report_id: str, error: str, attempts: int) -> None: ...


class TemplateRepository(TemplateProvider, Protocol):
    def initialize_template(
        self, template_id: str, name: str, description: str, content: str,
    ) -> None: ...
    def template_summaries(self) -> Iterable[Mapping[str, Any]]: ...
    def template_detail(self, template_id: str) -> dict | None: ...
    def save_template_draft(self, template_id: str, content: str, expected_revision: int) -> dict | None: ...
    def publish_template(self, template_id: str, expected_revision: int, created_by: str) -> dict | None: ...
    def restore_template_version(self, template_id: str, version: int, expected_revision: int) -> dict | None: ...
    def template_version_exists(self, template_id: str, version: int) -> bool: ...


class WorkerRepository(NotificationRepository, ReportRepository, Protocol):
    def begin_job(self) -> int: ...
    def finish_job(
        self, job_id: int, discovered: int, analyzed: int,
        sent: int, errors: int, last_error: str | None,
    ) -> None: ...
    def mark_source_result(
        self, source_id: str, interval_minutes: int,
        item_count: int, error: str | None = None,
    ) -> None: ...
    def source_is_due(self, source_id: str) -> bool: ...
    def source_state_exists(self, source_id: str) -> bool: ...
    def source_has_never_succeeded(self, source_id: str) -> bool: ...
    def item_count(self) -> int: ...
    def status_summary(self) -> dict: ...
